name: "Sungrow Inverter"
version: "0.4.62"
image: ghcr.io/voyanti/ha-sungrow
slug: "ha-sungrow"
description: "Sungrow Inverter Prebuilt"
init: false
startup: application
boot: auto
url: "https://github.com/heinrich321/voyanti-sungrow/"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  servers:
    - name: "SG1"
      serialnum: "A2340700442"
      server_type: "SUNGROW_INVERTER"
      connected_client: "Client1"
      modbus_id: 1
    - name: "SGL1"
      serialnum: "B2391405111"
      server_type: "SUNGROW_LOGGER"
      connected_client: "Client1"
      modbus_id: 247
    - name: "GM"
      serialnum: "unknown"
      server_type: "SUNGROW_METER"
      connected_client: "Client1"
      modbus_id: 2
      # PT: 1
      # CT: 320
  clients:
    - name: "Client1"
      type: "TCP"
      host: "10.0.0.15"
      port: 502
  pause_interval_seconds: 0.5
  midnight_sleep_enabled: true
  midnight_sleep_wakeup_after: 10
  mqtt_host: "localhost"
  mqtt_port: 1884
  # mqtt_host: "core-mosquitto"
  # mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_password: "mqtt"
  mwtt_ha_discovery_topic: "homeassistant"
  mqtt_base_topic: "modbus"
schema:
  servers:
    - name: str
      serialnum: str
      server_type: list(SUNGROW_INVERTER|SUNGROW_LOGGER|SUNGROW_METER)
      connected_client: str
      modbus_id: int(0,255)
      # PT: int?
      # CT: int?
  clients:
    - name: str
      type: list(TCP|RTU)
      host: str?
      port: int?
      baudrate: int?
      bytesize: int?
      parity: bool?
      stopbits: int?
  pause_interval_seconds: int
  midnight_sleep_enabled: bool
  midnight_sleep_wakeup_after: int
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str
  mqtt_password: password
  mwtt_ha_discovery_topic: str
  mqtt_base_topic: str
